num_clients: 10
num_rounds: 50
fraction_evaluate: 0

noniid:
  concentration: 0.1

server:
  momentum: 0.9
  learning_rate: 1.0
  reporting_fraction: 1.0

client:
  local_epochs: 5
  batch_size: 64
  lr: 0.01

defaults:
  - _self_
  - strategy: custom-fedavgm
  - model: resnet10
  - dataset: cifar10

num_cpus: 1
num_gpus: 0.5